import { CompletionItemKind } from 'vscode';
import { signatureToCompletion, signatureToHover } from '../../util';

const include = '(Requires: `#include <WinAPISys.au3>`)';

const signatures = {
  _WinAPI_LockWorkStation: {
    documentation: "Locks the workstation's display",
    label: '_WinAPI_LockWorkStation ( )',
    params: [],
  },
  _WinAPI_ShutdownBlockReasonCreate: {
    documentation:
      'Indicates that the system cannot be shut down and sets a reason string to be displayed to the user if system shutdown is initiated',
    label: '_WinAPI_ShutdownBlockReasonCreate ( $hWnd, $sText )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the main window of the application.',
      },
      {
        label: '$sText',
        documentation:
          'The string that explains the reason the application must block system shutdown.',
      },
    ],
  },
  _WinAPI_ShutdownBlockReasonDestroy: {
    documentation: 'Indicates that the system can be shut down and frees the reason string',
    label: '_WinAPI_ShutdownBlockReasonDestroy ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the main window of the application.',
      },
    ],
  },
  _WinAPI_ShutdownBlockReasonQuery: {
    documentation:
      'Retrieves the reason string set by the _WinAPI_ShutdownBlockReasonCreate() function',
    label: '_WinAPI_ShutdownBlockReasonQuery ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the main window of the application.',
      },
    ],
  },
  _WinAPI_SetWinEventHook: {
    documentation: 'Sets an event hook function for a range of events',
    label:
      '_WinAPI_SetWinEventHook ( $iEventMin, $iEventMax, $pEventProc [, $iPID = 0 [, $iThreadId = 0 [, $iFlags = 0]]] )',
    params: [
      {
        label: '$iEventMin',
        documentation:
          'The lowest event value in the range of events ($EVENT_*) that are handled by the hook function.',
      },
      {
        label: '$iEventMax',
        documentation:
          'The highest event value in the range of events ($EVENT_*) that are handled by the hook function.',
      },
      {
        label: '$pEventProc',
        documentation:
          'The address of an application-defined hook function that the system calls in response to events generated by an accessible object.',
      },
      {
        label: '$iPID',
        documentation:
          '**[optional]** The ID of the process from which the hook function receives events. If this parameter is 0 (Default), the hook function is associated with all existing processes on the current desktop.',
      },
      {
        label: '$iThreadId',
        documentation:
          '**[optional]** The ID of the thread from which the hook function receives events. If this parameter is 0 (Default),the hook function is associated with all existing threads on the current desktop.',
      },
      {
        label: '$iFlags',
        documentation:
          '**[optional]** The flags that specify the location of the hook function and of the events to be skipped.The following flags are valid: $WINEVENT_INCONTEXT $WINEVENT_OUTOFCONTEXT (Default) $WINEVENT_SKIPOWNPROCESS $WINEVENT_SKIPOWNTHREAD The following single flags, or flag combinations are valid: $WINEVENT_INCONTEXT $WINEVENT_OUTOFCONTEXT $WINEVENT_INCONTEXT | $WINEVENT_SKIPOWNPROCESS $WINEVENT_INCONTEXT | $WINEVENT_SKIPOWNTHREAD $WINEVENT_OUTOFCONTEXT | $WINEVENT_SKIPOWNPROCESS $WINEVENT_OUTOFCONTEXT | $WINEVENT_SKIPOWNTHREAD',
      },
    ],
  },
  _WinAPI_UnhookWinEvent: {
    documentation: 'Removes an event hook function',
    label: '_WinAPI_UnhookWinEvent ( $hEventHook )',
    params: [
      {
        label: '$hEventHook',
        documentation:
          'Handle to the event hook returned in the previous call to _WinAPI_SetWinEventHook().',
      },
    ],
  },
  _WinAPI_AddClipboardFormatListener: {
    documentation:
      'Places the given window in the system-maintained clipboard format listener list',
    label: '_WinAPI_AddClipboardFormatListener ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to be placed.',
      },
    ],
  },
  _WinAPI_GetClipboardSequenceNumber: {
    documentation: 'Retrieves the clipboard sequence number for the current window station',
    label: '_WinAPI_GetClipboardSequenceNumber ( )',
    params: [],
  },
  _WinAPI_RemoveClipboardFormatListener: {
    documentation:
      'Removes the given window from the system-maintained clipboard format listener list',
    label: '_WinAPI_RemoveClipboardFormatListener ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to be removed.',
      },
    ],
  },
  _WinAPI_GetEffectiveClientRect: {
    documentation:
      'Calculates the dimensions of a rectangle in the client area that contains all the specified controls',
    label: '_WinAPI_GetEffectiveClientRect ( $hWnd, $aCtrl [, $iStart = 0 [, $iEnd = -1]] )',
    params: [
      {
        label: '$hWnd',
        documentation: 'A handle to the window that has the client area to check.',
      },
      {
        label: '$aCtrl',
        documentation:
          'The array containing the handles or identifiers of the controls that should be included in the calculation of the client area. Also, it can be a single handle or control identifier.',
      },
      {
        label: '$iStart',
        documentation: '**[optional]** The index of array element that contains the first control.',
      },
      {
        label: '$iEnd',
        documentation: '**[optional]** The index of array element that contains the last control.',
      },
    ],
  },
  _WinAPI_GetMUILanguage: {
    documentation:
      'Gets the language currently in use by the common controls for a particular process',
    label: '_WinAPI_GetMUILanguage ( )',
    params: [],
  },
  _WinAPI_InitMUILanguage: {
    documentation:
      'Enables an application to specify a language to be used with the common controls that is different from the system language',
    label: '_WinAPI_InitMUILanguage ( $iLanguage )',
    params: [
      {
        label: '$iLanguage',
        documentation: 'The language identifier to be used by the common controls.',
      },
    ],
  },
  _WinAPI_LoadIconMetric: {
    documentation: 'Loads a specified icon resource with a client-specified system metric',
    label: '_WinAPI_LoadIconMetric ( $hInstance, $sName, $iMetric )',
    params: [
      {
        label: '$hInstance',
        documentation:
          'A handle to an instance of the module whose executable file contains the ' +
          'icon to be loaded.',
      },
      {
        label: '$sName',
        documentation:
          'The name of the icon resource, either a resource name, resource identifier, file name, ' +
          'or one of the IDI_* values.',
      },
      {
        label: '$iMetric',
        documentation:
          'A system metric value that directs the function to load a system-defined icon size. ' +
          'Use $LIM_SMALL or $LIM_LARGE.',
      },
    ],
  },
  _WinAPI_LoadIconWithScaleDown: {
    documentation:
      'Loads an icon and scales down a larger image instead of scaling up a smaller image',
    label: '_WinAPI_LoadIconWithScaleDown ( $hInstance, $sName, $iWidth, $iHeight )',
    params: [
      {
        label: '$hInstance',
        documentation:
          'A handle to an instance of the module whose executable file contains the ' +
          'icon to be loaded.',
      },
      {
        label: '$sName',
        documentation:
          'The name of the icon resource, either a resource name, resource identifier, file name, ' +
          'or one of the IDI_* values.',
      },
      {
        label: '$iWidth',
        documentation: 'The desired width, in pixels, of the icon.',
      },
      {
        label: '$iHeight',
        documentation: 'The desired height, in pixels, of the icon.',
      },
    ],
  },
  _WinAPI_MirrorIcon: {
    documentation:
      'Reverses (mirrors) icons so that they are displayed correctly on a mirrored device context',
    label: '_WinAPI_MirrorIcon ( $hIcon [, $bDelete = False] )',
    params: [
      {
        label: '$hIcon',
        documentation: 'Handle to the icon to be mirrored.',
      },
      {
        label: '$bDelete',
        documentation:
          '**[optional]** If True, deletes the original icon after mirroring. Default is False.',
      },
    ],
  },
  _WinAPI_GetDllDirectory: {
    documentation:
      'Retrieves the application-specific portion of the search path used to locate DLLs for the application',
    label: '_WinAPI_GetDllDirectory ( )',
    params: [],
  },
  _WinAPI_GetModuleHandleEx: {
    documentation: 'Retrieves a module handle for the specified module',
    label: '_WinAPI_GetModuleHandleEx ( $sModule [, $iFlags = 0] )',
    params: [
      {
        label: '$sModule',
        documentation:
          'The name of the module. If 0 or an empty string, the function returns a handle to the ' +
          'file used to create the calling process (.exe file).',
      },
      {
        label: '$iFlags',
        documentation:
          '[optional] Flags that modify the behavior of the function (GET_MODULE_HANDLE_EX_*). ' +
          'Default is 0.',
      },
    ],
  },
  _WinAPI_SetDllDirectory: {
    documentation: 'Adds a directory to the search path used to locate DLLs for the application',
    label: '_WinAPI_SetDllDirectory ( [$sDirPath = Default] )',
    params: [
      {
        label: '$sDirPath',
        documentation:
          '**[optional]** The directory to be added to the search path. If this parameter is an empty string (""), the call removes the current directory from the default DLL search order.If this parameter is not specified, the function restores the default search order (Default).',
      },
    ],
  },
  _WinAPI_CreateBuffer: {
    documentation: 'Allocates a block of memory from the internal library heap',
    label: '_WinAPI_CreateBuffer ( $iLength [, $pBuffer = 0 [, $bAbort = True]] )',
    params: [
      {
        label: '$iLength',
        documentation: 'The size of the memory block, in bytes, to allocate.',
      },
      {
        label: '$pBuffer',
        documentation:
          '[optional] A pointer to a buffer whose content will be copied to the newly allocated ' +
          'memory block. Default is 0.',
      },
      {
        label: '$bAbort',
        documentation:
          '[optional] If True, the function sets the @error flag and returns 0 if the allocation ' +
          'fails. Default is True.',
      },
    ],
  },
  _WinAPI_CreateBufferFromStruct: {
    documentation:
      "Allocates a block of memory from the internal library heap and initializes it with the structure's data",
    label: '_WinAPI_CreateBufferFromStruct ( $tStruct [, $pBuffer = 0 [, $bAbort = True]] )',
    params: [
      {
        label: '$tStruct',
        documentation: 'A structure whose data is copied into the newly allocated memory block.',
      },
      {
        label: '$pBuffer',
        documentation:
          '[optional] A pointer to a buffer whose content will be copied to the newly allocated ' +
          'memory block. Default is 0.',
      },
      {
        label: '$bAbort',
        documentation:
          '[optional] If True, the function sets the @error flag and returns 0 if the allocation ' +
          'fails. Default is True.',
      },
    ],
  },
  _WinAPI_CreateString: {
    documentation:
      'Copies a specified string to the newly allocated memory block and returns its pointer',
    label:
      '_WinAPI_CreateString ( $sString [, $pString = 0 [, $iLength = -1 [, $bUnicode = True [, $bAbort = True]]]] )',
    params: [
      {
        label: '$sString',
        documentation: 'The string to copy to the newly allocated memory block.',
      },
      {
        label: '$pString',
        documentation:
          '[optional] A pointer to a buffer to receive the copied string. Default is 0.',
      },
      {
        label: '$iLength',
        documentation:
          '[optional] The length of the string, in characters. Default is -1 (null-terminated).',
      },
      {
        label: '$bUnicode',
        documentation:
          '[optional] If True, creates a Unicode string; otherwise creates an ANSI string. ' +
          'Default is True.',
      },
      {
        label: '$bAbort',
        documentation:
          '[optional] If True, the function sets the @error flag and returns 0 if the allocation ' +
          'fails. Default is True.',
      },
    ],
  },
  _WinAPI_FreeMemory: {
    documentation: 'Frees a memory block in the internal library heap',
    label: '_WinAPI_FreeMemory ( $pMemory )',
    params: [
      {
        label: '$pMemory',
        documentation: 'A pointer to the valid memory block to be freed.',
      },
    ],
  },
  _WinAPI_GetMemorySize: {
    documentation: 'Retrieves the size of a memory block allocated from the internal library heap',
    label: '_WinAPI_GetMemorySize ( $pMemory )',
    params: [
      {
        label: '$pMemory',
        documentation: 'A pointer to the valid memory block whose size to be retrieved.',
      },
    ],
  },
  _WinAPI_IsMemory: {
    documentation:
      'Determines whether the specified pointer points to the memory block in the internal library heap',
    label: '_WinAPI_IsMemory ( $pMemory )',
    params: [
      {
        label: '$pMemory',
        documentation: 'A pointer to the memory block that to be tested.',
      },
    ],
  },
  _WinAPI_CompressBuffer: {
    documentation: 'Compresses a buffer with specified compression format and engine type',
    label:
      '_WinAPI_CompressBuffer ( $pUncompressedBuffer, $iUncompressedSize, $pCompressedBuffer, $iCompressedSize [, $iFormatAndEngine = 0x0002] )',
    params: [
      {
        label: '$pUncompressedBuffer',
        documentation: 'A pointer to the buffer that contains the data to compress.',
      },
      {
        label: '$iUncompressedSize',
        documentation: 'The size, in bytes, of the uncompressed buffer.',
      },
      {
        label: '$pCompressedBuffer',
        documentation: 'A pointer to the buffer that receives the compressed data.',
      },
      {
        label: '$iCompressedSize',
        documentation: 'The size, in bytes, of the compressed buffer.',
      },
      {
        label: '$iFormatAndEngine',
        documentation:
          '[optional] A value that specifies the compression format and engine. Default is 0x0002.',
      },
    ],
  },
  _WinAPI_ComputeCrc32: {
    documentation: 'Calculates the CRC32 checksum of a block of memory',
    label: '_WinAPI_ComputeCrc32 ( $pMemory, $iLength )',
    params: [
      {
        label: '$pMemory',
        documentation: 'A pointer to the memory block to compute the CRC32 checksum.',
      },
      {
        label: '$iLength',
        documentation: 'The number of bytes to include in the calculation.',
      },
    ],
  },
  _WinAPI_DecompressBuffer: {
    documentation: 'Decompresses an entire compressed buffer',
    label:
      '_WinAPI_DecompressBuffer ( $pUncompressedBuffer, $iUncompressedSize, $pCompressedBuffer, $iCompressedSize [, $iFormat = 0x0002] )',
    params: [
      {
        label: '$pUncompressedBuffer',
        documentation: 'A pointer to the buffer that receives the decompressed data.',
      },
      {
        label: '$iUncompressedSize',
        documentation: 'The size, in bytes, of the uncompressed buffer.',
      },
      {
        label: '$pCompressedBuffer',
        documentation: 'A pointer to the compressed data buffer.',
      },
      {
        label: '$iCompressedSize',
        documentation: 'The size, in bytes, of the compressed data buffer.',
      },
      {
        label: '$iFormat',
        documentation:
          '[optional] A value that specifies the compression format. Default is 0x0002.',
      },
    ],
  },
  _WinAPI_EqualMemory: {
    documentation:
      'Compares two blocks of memory to determine whether the specified number of bytes are identical',
    label: '_WinAPI_EqualMemory ( $pSource1, $pSource2, $iLength )',
    params: [
      {
        label: '$pSource1',
        documentation: 'A pointer to the first memory block to compare.',
      },
      {
        label: '$pSource2',
        documentation: 'A pointer to the second memory block to compare.',
      },
      {
        label: '$iLength',
        documentation: 'The number of bytes to compare.',
      },
    ],
  },
  _WinAPI_FillMemory: {
    documentation: 'Fills a block of memory with the given value',
    label: '_WinAPI_FillMemory ( $pMemory, $iLength [, $iValue = 0] )',
    params: [
      {
        label: '$pMemory',
        documentation: 'A pointer to the memory block to be filled.',
      },
      {
        label: '$iLength',
        documentation: 'The number of bytes to set.',
      },
      {
        label: '$iValue',
        documentation: '[optional] The value to be set. Default is 0.',
      },
    ],
  },
  _WinAPI_GetPhysicallyInstalledSystemMemory: {
    documentation: 'Retrieves the amount of RAM that is physically installed on the computer',
    label: '_WinAPI_GetPhysicallyInstalledSystemMemory ( )',
    params: [],
  },
  _WinAPI_GetSystemDEPPolicy: {
    documentation: 'Gets the data execution prevention (DEP) policy setting for the system',
    label: '_WinAPI_GetSystemDEPPolicy ( )',
    params: [],
  },
  _WinAPI_IsBadCodePtr: {
    documentation:
      'Determines whether the calling process has read access to the memory at the specified address',
    label: '_WinAPI_IsBadCodePtr ( $pAddress )',
    params: [
      {
        label: '$pAddress',
        documentation: 'A pointer to a memory address.',
      },
    ],
  },
  _WinAPI_IsBadReadPtr: {
    documentation:
      'Verifies that the calling process has read access to the specified range of memory',
    label: '_WinAPI_IsBadReadPtr ( $pAddress, $iLength )',
    params: [
      {
        label: '$pAddress',
        documentation: 'A pointer to the starting memory address.',
      },
      {
        label: '$iLength',
        documentation: 'The size, in bytes, of the memory block.',
      },
    ],
  },
  _WinAPI_IsBadStringPtr: {
    documentation:
      'Verifies that the calling process has read access to the specified range of memory',
    label: '_WinAPI_IsBadStringPtr ( $pAddress, $iLength )',
    params: [
      {
        label: '$pAddress',
        documentation: 'A pointer to a null-terminated string.',
      },
      {
        label: '$iLength',
        documentation: 'The maximum size of the string, in TCHARs.',
      },
    ],
  },
  _WinAPI_IsBadWritePtr: {
    documentation:
      'Verifies that the calling process has write access to the specified range of memory',
    label: '_WinAPI_IsBadWritePtr ( $pAddress, $iLength )',
    params: [
      {
        label: '$pAddress',
        documentation: 'A pointer to the starting memory address.',
      },
      {
        label: '$iLength',
        documentation: 'The size, in bytes, of the memory block.',
      },
    ],
  },
  _WinAPI_MoveMemory: {
    documentation: 'Moves a block of memory from one location to another',
    label: '_WinAPI_MoveMemory ( $pDestination, $pSource, $iLength )',
    params: [
      {
        label: '$pDestination',
        documentation: 'A pointer to the destination memory block.',
      },
      {
        label: '$pSource',
        documentation: 'A pointer to the source memory block.',
      },
      {
        label: '$iLength',
        documentation: 'The number of bytes to move.',
      },
    ],
  },
  _WinAPI_ZeroMemory: {
    documentation: 'Fills a block of memory with zeros',
    label: '_WinAPI_ZeroMemory ( $pMemory, $iLength )',
    params: [
      {
        label: '$pMemory',
        documentation: 'A pointer to the memory block to be filled with zeros.',
      },
      {
        label: '$iLength',
        documentation: 'The number of bytes to set to zero.',
      },
    ],
  },
  _WinAPI_GetDefaultPrinter: {
    documentation:
      'Retrieves the printer name of the default printer for the current user on the local computer',
    label: '_WinAPI_GetDefaultPrinter ( )',
    params: [],
  },
  _WinAPI_GetPwrCapabilities: {
    documentation: 'Retrieves information about the system power capabilities',
    label: '_WinAPI_GetPwrCapabilities ( )',
    params: [],
  },
  _WinAPI_GetSystemPowerStatus: {
    documentation: 'Retrieves the power status of the system',
    label: '_WinAPI_GetSystemPowerStatus ( )',
    params: [],
  },
  _WinAPI_RegisterPowerSettingNotification: {
    documentation:
      'Registers the application to receive power setting notifications for the specific power setting event',
    label: '_WinAPI_RegisterPowerSettingNotification ( $hWnd, $sGUID )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window that receives the change or notification messages.',
      },
      {
        label: '$sGUID',
        documentation:
          'The GUID that specifies the power setting for which notifications are to be sent.',
      },
    ],
  },
  _WinAPI_UnregisterPowerSettingNotification: {
    documentation: 'Unregisters the power setting notification',
    label: '_WinAPI_UnregisterPowerSettingNotification ( $hNotify )',
    params: [
      {
        label: '$hNotify',
        documentation:
          'Handle returned from the _WinAPI_RegisterPowerSettingNotification() function.',
      },
    ],
  },
  _WinAPI_CloseDesktop: {
    documentation: 'Closes an open handle to a desktop object',
    label: '_WinAPI_CloseDesktop ( $hDesktop )',
    params: [
      {
        label: '$hDesktop',
        documentation: 'Handle to the desktop to be closed.',
      },
    ],
  },
  _WinAPI_CloseWindowStation: {
    documentation: 'Closes an open window station handle',
    label: '_WinAPI_CloseWindowStation ( $hStation )',
    params: [
      {
        label: '$hStation',
        documentation: 'Handle to the window station to be closed.',
      },
    ],
  },
  _WinAPI_CreateDesktop: {
    documentation:
      'Creates a new desktop, associates it with the current window station of the calling process',
    label:
      '_WinAPI_CreateDesktop ( $sName [, $iAccess = 0x0002 [, $iFlags = 0 [, $iHeap = 0 [, $tSecurity = 0]]]] )',
    params: [
      {
        label: '$sName',
        documentation: 'The name of the desktop to be created.',
      },
      {
        label: '$iAccess',
        documentation:
          '[optional] The requested access to the desktop. This parameter can be one or more ' +
          'DESKTOP_* values. Default is 0x0002.',
      },
      {
        label: '$iFlags',
        documentation: '[optional] Flags for desktop creation. Default is 0.',
      },
      {
        label: '$iHeap',
        documentation: '[optional] The size of the desktop heap. Default is 0.',
      },
      {
        label: '$tSecurity',
        documentation: '[optional] A pointer to a SECURITY_ATTRIBUTES structure. Default is 0.',
      },
    ],
  },
  _WinAPI_CreateWindowStation: {
    documentation:
      'Creates a window station object, associates it with the calling process, and assigns it to the current session',
    label:
      "_WinAPI_CreateWindowStation ( [$sName = '' [, $iAccess = 0 [, $iFlags = 0 [, $tSecurity = 0]]]] )",
    params: [
      {
        label: '$sName',
        documentation: "[optional] The name of the window station to be created. Default is ''.",
      },
      {
        label: '$iAccess',
        documentation:
          '[optional] The requested access to the window station. This parameter can be one or ' +
          'more WINSTA_* values. Default is 0.',
      },
      {
        label: '$iFlags',
        documentation:
          '[optional] Flags for window station creation (for example, $CWF_CREATE_ONLY). ' +
          'Default is 0.',
      },
      {
        label: '$tSecurity',
        documentation: '[optional] A pointer to a SECURITY_ATTRIBUTES structure. Default is 0.',
      },
    ],
  },
  _WinAPI_EnumDesktops: {
    documentation:
      'Enumerates all desktops associated with the specified window station of the calling process',
    label: '_WinAPI_EnumDesktops ( $hStation )',
    params: [
      {
        label: '$hStation',
        documentation:
          'Handle to a window station. The WINSTA_ENUMDESKTOPS access right is required.',
      },
    ],
  },
  _WinAPI_EnumDesktopWindows: {
    documentation: 'Enumerates all top-level windows associated with the specified desktop',
    label: '_WinAPI_EnumDesktopWindows ( $hDesktop [, $bVisible = True] )',
    params: [
      {
        label: '$hDesktop',
        documentation:
          'Handle to the desktop whose top-level windows are to be enumerated. The ' +
          'DESKTOP_READOBJECTS access right is required.',
      },
      {
        label: '$bVisible',
        documentation: '[optional] If True, enumerates only visible windows. Default is True.',
      },
    ],
  },
  _WinAPI_EnumWindowStations: {
    documentation: 'Enumerates all window stations in the current session',
    label: '_WinAPI_EnumWindowStations ( )',
    params: [],
  },
  _WinAPI_GetProcessWindowStation: {
    documentation: 'Retrieves a handle to the current window station for the calling process',
    label: '_WinAPI_GetProcessWindowStation ( )',
    params: [],
  },
  _WinAPI_GetUserObjectInformation: {
    documentation: 'Retrieves information about the specified window station or desktop object',
    label: '_WinAPI_GetUserObjectInformation ( $hObject, $iIndex )',
    params: [
      {
        label: '$hObject',
        documentation: 'Handle to the window station or desktop object.',
      },
      {
        label: '$iIndex',
        documentation: 'The information to retrieve (UOI_*).',
      },
    ],
  },
  _WinAPI_OpenDesktop: {
    documentation: 'Opens the specified desktop object',
    label: '_WinAPI_OpenDesktop ( $sName [, $iAccess = 0 [, $iFlags = 0 [, $bInherit = False]]] )',
    params: [
      {
        label: '$sName',
        documentation: 'The name of the desktop to be opened.',
      },
      {
        label: '$iAccess',
        documentation:
          '[optional] The requested access to the desktop. This parameter can be one or more ' +
          'DESKTOP_* values. Default is 0.',
      },
      {
        label: '$iFlags',
        documentation: '[optional] Flags for opening the desktop. Default is 0.',
      },
      {
        label: '$bInherit',
        documentation: '[optional] If True, the returned handle is inheritable. Default is False.',
      },
    ],
  },
  _WinAPI_OpenInputDesktop: {
    documentation: 'Opens the desktop that receives user input',
    label: '_WinAPI_OpenInputDesktop ( [$iAccess = 0 [, $iFlags = 0 [, $bInherit = False]]] )',
    params: [
      {
        label: '$iAccess',
        documentation:
          '[optional] The requested access to the desktop. This parameter can be one or more ' +
          'DESKTOP_* values. Default is 0.',
      },
      {
        label: '$iFlags',
        documentation: '[optional] Flags for opening the desktop. Default is 0.',
      },
      {
        label: '$bInherit',
        documentation: '[optional] If True, the returned handle is inheritable. Default is False.',
      },
    ],
  },
  _WinAPI_OpenWindowStation: {
    documentation: 'Opens the specified window station',
    label: '_WinAPI_OpenWindowStation ( $sName [, $iAccess = 0 [, $bInherit = False]] )',
    params: [
      {
        label: '$sName',
        documentation: 'The name of the window station to be opened.',
      },
      {
        label: '$iAccess',
        documentation:
          '[optional] The requested access to the window station. This parameter can be one or ' +
          'more WINSTA_* values. Default is 0.',
      },
      {
        label: '$bInherit',
        documentation: '[optional] If True, the returned handle is inheritable. Default is False.',
      },
    ],
  },
  _WinAPI_SetProcessWindowStation: {
    documentation: 'Assigns the specified window station to the calling process',
    label: '_WinAPI_SetProcessWindowStation ( $hStation )',
    params: [
      {
        label: '$hStation',
        documentation: 'Handle to the window station to be assigned to the calling process.',
      },
    ],
  },
  _WinAPI_SetUserObjectInformation: {
    documentation: 'Sets information about the specified window station or desktop object',
    label: '_WinAPI_SetUserObjectInformation ( $hObject, $iIndex, $tData )',
    params: [
      {
        label: '$hObject',
        documentation: 'Handle to the window station or desktop object.',
      },
      {
        label: '$iIndex',
        documentation: 'The information to set (UOI_FLAGS).',
      },
      {
        label: '$tData',
        documentation: 'The data to set. The type depends on the information class.',
      },
    ],
  },
  _WinAPI_SwitchDesktop: {
    documentation: 'Makes the specified desktop visible and activates it',
    label: '_WinAPI_SwitchDesktop ( $hDesktop )',
    params: [
      {
        label: '$hDesktop',
        documentation: 'Handle to the desktop to make visible and activate.',
      },
    ],
  },
  _WinAPI_EnumPageFiles: {
    documentation: 'Retrieves information for each installed pagefile in the system',
    label: '_WinAPI_EnumPageFiles ( )',
    params: [],
  },
  _WinAPI_GetCurrentHwProfile: {
    documentation:
      'Retrieves information about the current hardware profile for the local computer',
    label: '_WinAPI_GetCurrentHwProfile ( )',
    params: [],
  },
  _WinAPI_GetHandleInformation: {
    documentation: 'Retrieves certain properties of an object handle',
    label: '_WinAPI_GetHandleInformation ( $hObject )',
    params: [
      {
        label: '$hObject',
        documentation: 'A handle to an object.',
      },
    ],
  },
  _WinAPI_GetPerformanceInfo: {
    documentation: 'Retrieves the performance information',
    label: '_WinAPI_GetPerformanceInfo ( )',
    params: [],
  },
  _WinAPI_GetProcessShutdownParameters: {
    documentation: 'Retrieves the shutdown parameters for the currently calling process',
    label: '_WinAPI_GetProcessShutdownParameters ( )',
    params: [],
  },
  _WinAPI_GetStartupInfo: {
    documentation:
      'Retrieves the contents of the STARTUPINFO structure that was specified when the calling process was created',
    label: '_WinAPI_GetStartupInfo ( )',
    params: [],
  },
  _WinAPI_GetSystemInfo: {
    documentation: 'Retrieves information about the current system',
    label: '_WinAPI_GetSystemInfo ( )',
    params: [],
  },
  _WinAPI_GetSystemTimes: {
    documentation: 'Retrieves system timing information',
    label: '_WinAPI_GetSystemTimes ( )',
    params: [],
  },
  _WinAPI_GetSystemWow64Directory: {
    documentation: 'Retrieves the path of the system directory used by WOW64',
    label: '_WinAPI_GetSystemWow64Directory ( )',
    params: [],
  },
  _WinAPI_GetTickCount: {
    documentation:
      'Retrieves the number of milliseconds that have elapsed since the system was started',
    label: '_WinAPI_GetTickCount ( )',
    params: [],
  },
  _WinAPI_GetTickCount64: {
    documentation:
      'Retrieves the number of milliseconds that have elapsed since the system was started',
    label: '_WinAPI_GetTickCount64 ( )',
    params: [],
  },
  _WinAPI_GetVersion: {
    documentation: 'Retrieves version of the current operating system',
    label: '_WinAPI_GetVersion ( )',
    params: [],
  },
  _WinAPI_GetVersionEx: {
    documentation: 'Retrieves information about the current operating system',
    label: '_WinAPI_GetVersionEx ( )',
    params: [],
  },
  _WinAPI_IsProcessorFeaturePresent: {
    documentation:
      'Determines whether the specified processor feature is supported by the current computer',
    label: '_WinAPI_IsProcessorFeaturePresent ( $iFeature )',
    params: [
      {
        label: '$iFeature',
        documentation: 'The processor feature to be tested ($PF_*).',
      },
    ],
  },
  _WinAPI_QueryPerformanceCounter: {
    documentation: 'Retrieves the current value of the high-resolution performance counter',
    label: '_WinAPI_QueryPerformanceCounter ( )',
    params: [],
  },
  _WinAPI_QueryPerformanceFrequency: {
    documentation: 'Retrieves the frequency of the high-resolution performance counter',
    label: '_WinAPI_QueryPerformanceFrequency ( )',
    params: [],
  },
  _WinAPI_SetProcessShutdownParameters: {
    documentation:
      'Sets a shutdown order for a process relative to the other processes in the system',
    label: '_WinAPI_SetProcessShutdownParameters ( $iLevel [, $bDialog = False] )',
    params: [
      {
        label: '$iLevel',
        documentation: 'The shutdown priority of the calling process.',
      },
      {
        label: '$bDialog',
        documentation:
          '[optional] If True, the system displays a shutdown dialog when the process is shutting down. Default is False.',
      },
    ],
  },
  _WinAPI_ActivateKeyboardLayout: {
    documentation: 'Sets the input locale identifier for the calling thread or the current process',
    label: '_WinAPI_ActivateKeyboardLayout ( $hLocale [, $iFlag = 0] )',
    params: [
      {
        label: '$hLocale',
        documentation: 'Input locale identifier (HKL) to be activated, or $HKL_NEXT/$HKL_PREV.',
      },
      {
        label: '$iFlag',
        documentation:
          '[optional] Flags specifying how the input locale identifier is to be activated (KLF_*). Default is 0.',
      },
    ],
  },
  _WinAPI_DefRawInputProc: {
    documentation:
      'Calls the default raw input procedure to process the raw input messages that an application does not process',
    label: '_WinAPI_DefRawInputProc ( $paRawInput, $iInput )',
    params: [
      {
        label: '$paRawInput',
        documentation:
          'A pointer to an array of $tagRAWINPUT structures that contain the raw input.',
      },
      {
        label: '$iInput',
        documentation: 'The number of $tagRAWINPUT structures in the array.',
      },
    ],
  },
  _WinAPI_EnumRawInputDevices: {
    documentation: 'Enumerates the raw input devices attached to the system',
    label: '_WinAPI_EnumRawInputDevices ( )',
    params: [],
  },
  _WinAPI_GetActiveWindow: {
    documentation:
      "Retrieves the window handle to the active window attached to the calling process's message queue",
    label: '_WinAPI_GetActiveWindow ( )',
    params: [],
  },
  _WinAPI_GetIdleTime: {
    documentation: 'Retrieves the time that has elapsed since the last input',
    label: '_WinAPI_GetIdleTime ( )',
    params: [],
  },
  _WinAPI_GetKeyboardLayout: {
    documentation: 'Retrieves the active input locale identifier for the specified window',
    label: '_WinAPI_GetKeyboardLayout ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation:
          '[optional] Handle to the window to query. If omitted, retrieves the input locale identifier for the calling thread.',
      },
    ],
  },
  _WinAPI_GetKeyboardLayoutList: {
    documentation:
      'Retrieves the all input locale identifiers corresponding to the current set of input locales in the system',
    label: '_WinAPI_GetKeyboardLayoutList ( )',
    params: [],
  },
  _WinAPI_GetKeyboardState: {
    documentation: 'Copies the status of the 256 virtual keys to the specified buffer',
    label: '_WinAPI_GetKeyboardState ( )',
    params: [],
  },
  _WinAPI_GetKeyboardType: {
    documentation: 'Retrieves information about the current keyboard',
    label: '_WinAPI_GetKeyboardType ( $iType )',
    params: [
      {
        label: '$iType',
        documentation:
          'Specifies the type of keyboard information to be returned. 0: Keyboard type. ' +
          '1: Keyboard subtype. 2: Number of function keys.',
      },
    ],
  },
  _WinAPI_GetKeyNameText: {
    documentation: 'Retrieves a string that represents the name of a key',
    label: '_WinAPI_GetKeyNameText ( $lParam )',
    params: [
      {
        label: '$lParam',
        documentation:
          'The second parameter of the keyboard message from which the keystroke message ' +
          'parameters were obtained.',
      },
    ],
  },
  _WinAPI_GetKeyState: {
    documentation: 'Retrieves the status of the specified virtual key',
    label: '_WinAPI_GetKeyState ( $vKey )',
    params: [
      {
        label: '$vKey',
        documentation:
          'A virtual-key code. For letters and digits, use the uppercase letter or digit ' +
          'character value.',
      },
    ],
  },
  _WinAPI_GetRawInputBuffer: {
    documentation: 'Performs a buffered read of the raw input data',
    label: '_WinAPI_GetRawInputBuffer ( $pBuffer, $iLength )',
    params: [
      {
        label: '$pBuffer',
        documentation: 'A pointer to the buffer that receives the raw input data.',
      },
      {
        label: '$iLength',
        documentation: 'The size, in bytes, of the buffer pointed to by $pBuffer.',
      },
    ],
  },
  _WinAPI_GetRawInputBufferLength: {
    documentation:
      'Retrieves the required buffer size to call the _WinAPI_GetRawInputBuffer() function',
    label: '_WinAPI_GetRawInputBufferLength ( )',
    params: [],
  },
  _WinAPI_GetRawInputData: {
    documentation: 'Retrieves the raw input from the specified device',
    label: '_WinAPI_GetRawInputData ( $hRawInput, $pBuffer, $iLength, $iFlag )',
    params: [
      {
        label: '$hRawInput',
        documentation: 'A handle to the RAWINPUT structure that contains the raw input data.',
      },
      {
        label: '$pBuffer',
        documentation: 'A pointer to a buffer that receives the raw input data.',
      },
      {
        label: '$iLength',
        documentation: 'The size, in bytes, of the buffer pointed to by $pBuffer.',
      },
      {
        label: '$iFlag',
        documentation:
          'Specifies what data will be returned in $pBuffer. This parameter can be $RID_HEADER or $RID_INPUT.',
      },
    ],
  },
  _WinAPI_GetRawInputDeviceInfo: {
    documentation: 'Retrieves information about the raw input device',
    label: '_WinAPI_GetRawInputDeviceInfo ( $hDevice, $pBuffer, $iLength, $iFlag )',
    params: [
      {
        label: '$hDevice',
        documentation: 'A handle to the raw input device.',
      },
      {
        label: '$pBuffer',
        documentation: 'A pointer to a buffer that receives the information.',
      },
      {
        label: '$iLength',
        documentation: 'The size, in bytes, of the buffer pointed to by $pBuffer.',
      },
      {
        label: '$iFlag',
        documentation: 'The type of information to retrieve (RIDI_*).',
      },
    ],
  },
  _WinAPI_GetRegisteredRawInputDevices: {
    documentation:
      'Retrieves the information about the raw input devices for the current application',
    label: '_WinAPI_GetRegisteredRawInputDevices ( $pBuffer, $iLength )',
    params: [
      {
        label: '$pBuffer',
        documentation:
          'A pointer to a buffer that receives the device information for the current application.',
      },
      {
        label: '$iLength',
        documentation: 'The size, in bytes, of the buffer pointed to by $pBuffer.',
      },
    ],
  },
  _WinAPI_IsLoadKBLayout: {
    documentation: 'Determines whether the specified input locale loaded into the system',
    label: '_WinAPI_IsLoadKBLayout ( $iLanguage )',
    params: [
      {
        label: '$iLanguage',
        documentation: 'The input locale identifier.',
      },
    ],
  },
  _WinAPI_IsWindowEnabled: {
    documentation:
      'Determines whether the specified window is enabled for mouse and keyboard input',
    label: '_WinAPI_IsWindowEnabled ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window.',
      },
    ],
  },
  _WinAPI_Keybd_Event: {
    documentation: 'Synthesizes a keystroke',
    label: '_WinAPI_Keybd_Event ( $vKey, $iFlags [, $iScanCode = 0 [, $iExtraInfo = 0]] )',
    params: [
      {
        label: '$vKey',
        documentation: 'A virtual-key code that identifies the key to simulate.',
      },
      {
        label: '$iFlags',
        documentation: 'The function options. Can be a combination of KEYEVENTF_* flags.',
      },
      {
        label: '$iScanCode',
        documentation: '[optional] A hardware scan code for the key. Default is 0.',
      },
      {
        label: '$iExtraInfo',
        documentation:
          '[optional] An additional value associated with the keystroke. Default is 0.',
      },
    ],
  },
  _WinAPI_LoadKeyboardLayout: {
    documentation: 'Loads a new input locale identifier into the system',
    label: '_WinAPI_LoadKeyboardLayout ( $iLanguage [, $iFlag = 0] )',
    params: [
      {
        label: '$iLanguage',
        documentation: 'The input locale identifier.',
      },
      {
        label: '$iFlag',
        documentation:
          '[optional] Specifies how the input locale identifier is to be loaded (KLF_*). Default is 0.',
      },
    ],
  },
  _WinAPI_MapVirtualKey: {
    documentation:
      'Translates a virtual-key code into a scan code or character value, or translates a scan code into a virtual-key code',
    label: '_WinAPI_MapVirtualKey ( $iCode, $iType [, $hLocale = 0] )',
    params: [
      {
        label: '$iCode',
        documentation: 'The value to be translated.',
      },
      {
        label: '$iType',
        documentation: 'The translation to be performed.',
      },
      {
        label: '$hLocale',
        documentation:
          '[optional] Input locale identifier for the layout to translate with. Default is 0.',
      },
    ],
  },
  _WinAPI_RegisterHotKey: {
    documentation: 'Defines a system-wide hot key',
    label: '_WinAPI_RegisterHotKey ( $hWnd, $iID, $iModifiers, $vKey )',
    params: [
      {
        label: '$hWnd',
        documentation:
          'Handle to the window that will receive WM_HOTKEY messages generated by the hot key. ' +
          'If this parameter is 0, WM_HOTKEY messages are posted to the message queue of the ' +
          'calling thread and must be processed in the message loop.',
      },
      {
        label: '$iID',
        documentation:
          'Specifies the identifier of the hot key. An application must specify an id value in the range 0x0000 through 0xBFFF.',
      },
      {
        label: '$iModifiers',
        documentation:
          'Specifies keys that must be pressed in combination with the key specified by the $vKey ' +
          'parameter in order to generate the WM_HOTKEY message. The $iModifiers parameter can be ' +
          'a combination of the following values. $MOD_ALT $MOD_CONTROL $MOD_SHIFT $MOD_WIN ' +
          'Windows 7 or later $MOD_NOREPEAT',
      },
      {
        label: '$vKey',
        documentation: 'Specifies the virtual-key code of the hot key ($VK_*).',
      },
    ],
  },
  _WinAPI_RegisterRawInputDevices: {
    documentation: 'Registers the devices that supply the raw input data',
    label: '_WinAPI_RegisterRawInputDevices ( $paDevice [, $iCount = 1] )',
    params: [
      {
        label: '$paDevice',
        documentation:
          'A pointer to an array of $tagRAWINPUTDEVICE structures that represent the devices that supply the raw input.',
      },
      {
        label: '$iCount',
        documentation: '[optional] The number of entries in the array. Default is 1.',
      },
    ],
  },
  _WinAPI_SetActiveWindow: {
    documentation: 'Activates the specified window',
    label: '_WinAPI_SetActiveWindow ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the top-level window to be activated.',
      },
    ],
  },
  _WinAPI_SetKeyboardLayout: {
    documentation: 'Sets an input locale identifier to the specified window',
    label: '_WinAPI_SetKeyboardLayout ( $hWnd, $iLanguage [, $iFlags = 0] )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to set input locale identifier.',
      },
      {
        label: '$iLanguage',
        documentation: 'The input locale identifier.',
      },
      {
        label: '$iFlags',
        documentation:
          '[optional] The new input locale. This parameter can be one or more of the following ' +
          'values. $INPUTLANGCHANGE_BACKWARD $INPUTLANGCHANGE_FORWARD ' +
          '$INPUTLANGCHANGE_SYSCHARSET',
      },
    ],
  },
  _WinAPI_SetKeyboardState: {
    documentation:
      "Copies a 256-byte array of keyboard key states into the calling process's keyboard input-state table",
    label: '_WinAPI_SetKeyboardState ( $tState )',
    params: [
      {
        label: '$tState',
        documentation: '"byte[256]" structure that contains keyboard key states.',
      },
    ],
  },
  _WinAPI_TrackMouseEvent: {
    documentation:
      'Posts messages when the mouse pointer leaves a window or hovers over a window for a specified amount of time',
    label: '_WinAPI_TrackMouseEvent ( $hWnd, $iFlags [, $iTime = -1] )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to track.',
      },
      {
        label: '$iFlags',
        documentation:
          'The services requested. This parameter can be a combination of the following values. ' +
          '$TME_CANCEL $TME_HOVER $TME_LEAVE $TME_NONCLIENT $TME_QUERY',
      },
      {
        label: '$iTime',
        documentation:
          '[optional] The hover time-out (if $TME_HOVER was specified in $Flags), in milliseconds. ' +
          'Can be (-1) (Default), which means to use the system default hover time-out.',
      },
    ],
  },
  _WinAPI_UnloadKeyboardLayout: {
    documentation: 'Unloads an input locale identifier',
    label: '_WinAPI_UnloadKeyboardLayout ( $hLocale )',
    params: [
      {
        label: '$hLocale',
        documentation: 'The input locale identifier to be unloaded.',
      },
    ],
  },
  _WinAPI_UnregisterHotKey: {
    documentation: 'Frees a hot key previously registered by the calling thread',
    label: '_WinAPI_UnregisterHotKey ( $hWnd, $iID )',
    params: [
      {
        label: '$hWnd',
        documentation:
          'Handle to the window associated with the hot key to be freed. This parameter should be 0 ' +
          'if the hot key is not associated with a window.',
      },
      {
        label: '$iID',
        documentation: 'Specifies the identifier of the hot key to be freed.',
      },
    ],
  },
  _WinAPI_AdjustWindowRectEx: {
    documentation:
      'Calculates the required size of the window rectangle, based on the desired size of the client rectangle',
    label:
      '_WinAPI_AdjustWindowRectEx ( ByRef $tRECT, $iStyle [, $iExStyle = 0 [, $bMenu = False]] )',
    params: [
      {
        label: 'ByRef $tRECT',
        documentation:
          '$tagRECT structure that contains the coordinates of the desired client area. This structure must be created before function call.',
      },
      {
        label: '$iStyle',
        documentation:
          'The window style of the window whose required size is to be calculated. Note that you cannot specify the $WS_OVERLAPPED style.',
      },
      {
        label: '$iExStyle',
        documentation:
          '**[optional]** The extended window style of the window whose required size is to be calculated.',
      },
      {
        label: '$bMenu',
        documentation: '**[optional]** Specifies whether the window has a menu.',
      },
    ],
  },
  _WinAPI_AnimateWindow: {
    documentation: 'Enables you to produce special effects when showing or hiding windows',
    label: '_WinAPI_AnimateWindow ( $hWnd, $iFlags [, $iDuration = 1000] )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to animate.',
      },
      {
        label: '$iFlags',
        documentation: 'The flags that specify the type of animation.',
      },
      {
        label: '$iDuration',
        documentation:
          '**[optional]** Specifies how long it takes to play the animation, in milliseconds.',
      },
    ],
  },
  _WinAPI_BeginDeferWindowPos: {
    documentation: 'Allocates memory for a multiple-window-position structure',
    label: '_WinAPI_BeginDeferWindowPos ( [$iAmount = 1] )',
    params: [
      {
        label: '$iAmount',
        documentation:
          '**[optional]** The initial number of windows for which to store position information.',
      },
    ],
  },
  _WinAPI_BringWindowToTop: {
    documentation: 'Brings the specified window to the top of the Z order',
    label: '_WinAPI_BringWindowToTop ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to bring to the top of the Z order.',
      },
    ],
  },
  _WinAPI_BroadcastSystemMessage: {
    documentation: 'Sends a message to the specified recipients',
    label:
      '_WinAPI_BroadcastSystemMessage ( $iMsg [, $wParam = 0 [, $lParam = 0 [, $iFlags = 0 [, $iRecipients = 0]]]] )',
    params: [
      {
        label: '$iMsg',
        documentation: 'The message to be sent.',
      },
      {
        label: '$wParam',
        documentation: '**[optional]** The message-specific information.',
      },
      {
        label: '$lParam',
        documentation: '**[optional]** The message-specific information.',
      },
      {
        label: '$iFlags',
        documentation: '**[optional]** The broadcast option.',
      },
      {
        label: '$iRecipients',
        documentation: '**[optional]** The recipients of the message.',
      },
    ],
  },
  _WinAPI_CallWindowProcW: {
    documentation: 'Passes message information to the specified window procedure',
    label: '_WinAPI_CallWindowProcW ( $pPrevWndProc, $hWnd, $iMsg, $wParam, $lParam )',
    params: [
      {
        label: '$pPrevWndProc',
        documentation:
          'The address of a previous window procedure, or a special internal value meaningful only to [_WinAPI_CallWindowProcW()]',
      },
      {
        label: '$hWnd',
        documentation: 'A handle to the window procedure that received the message.',
      },
      {
        label: '$iMsg',
        documentation: 'The message.',
      },
      {
        label: '$wParam',
        documentation:
          'Additional message-specific information. The content of this parameter depends on the message.',
      },
      {
        label: '$lParam',
        documentation:
          'Additional message-specific information. The content of this parameter depends on the message.',
      },
    ],
  },
  _WinAPI_CascadeWindows: {
    documentation: 'Cascades the specified child windows of the specified parent window',
    label:
      '_WinAPI_CascadeWindows ( $aWnds [, $tRECT = 0 [, $hParent = 0 [, $iFlags = 0 [, $iStart = 0 [, $iEnd = -1]]]]] )',
    params: [
      {
        label: '$aWnds',
        documentation: 'The array of handles to the child windows to arrange.',
      },
      {
        label: '$tRECT',
        documentation:
          '**[optional]** $tagRECT structure that specifies the rectangular area, in client coordinates, within which the windows are arranged.',
      },
      {
        label: '$hParent',
        documentation:
          '**[optional]** Handle to the parent window. If this parameter is 0 (Default), the desktop window is assumed.',
      },
      {
        label: '$iFlags',
        documentation: '**[optional]** A cascade flag',
      },
      {
        label: '$iStart',
        documentation: '**[optional]** The index of array to start arranging at.',
      },
      {
        label: '$iEnd',
        documentation: '**[optional]** The index of array to stop arranging at.',
      },
    ],
  },
  _WinAPI_ChangeWindowMessageFilterEx: {
    documentation:
      'Modifies the User Interface Privilege Isolation (UIPI) message filter for a specified window',
    label: '_WinAPI_ChangeWindowMessageFilterEx ( $hWnd, $iMsg, $iAction )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window whose UIPI message filter is to be modified.',
      },
      {
        label: '$iMsg',
        documentation: 'The message that the message filter allows through or blocks.',
      },
      {
        label: '$iAction',
        documentation: 'The action to be performed.',
      },
    ],
  },
  _WinAPI_ChildWindowFromPointEx: {
    documentation:
      'Determines which, if any, of the child windows belonging to the specified parent window contains the specified point',
    label: '_WinAPI_ChildWindowFromPointEx ( $hWnd, $tPOINT [, $iFlags = 0] )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the parent window.',
      },
      {
        label: '$tPOINT',
        documentation:
          '$tagPOINT structure that defines the client coordinates (relative to hwndParent) of the point to be checked.',
      },
      {
        label: '$iFlags',
        documentation: '**[optional]** The flags that specify which child windows to skip.',
      },
    ],
  },
  _WinAPI_CloseWindow: {
    documentation: 'Minimizes (but does not destroy) the specified window',
    label: '_WinAPI_CloseWindow ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to be minimized.',
      },
    ],
  },
  _WinAPI_DeferWindowPos: {
    documentation:
      'Updates the specified multiple-window-position structure for the specified window',
    label:
      '_WinAPI_DeferWindowPos ( $hInfo, $hWnd, $hAfter, $iX, $iY, $iWidth, $iHeight, $iFlags )',
    params: [
      {
        label: '$hInfo',
        documentation:
          'Handle to a multiple-window-position structure that contains size and position information for one or more windows.',
      },
      {
        label: '$hWnd',
        documentation:
          'Handle to the window for which update information is stored in the structure. All windows in a multiple-window-position structure must have the same parent.',
      },
      {
        label: '$hAfter',
        documentation: 'Handle to the window that precedes the positioned window in the Z order.',
      },
      {
        label: '$iX',
        documentation: "The x-coordinate of the window's upper-left corner.",
      },
      {
        label: '$iY',
        documentation: "The y-coordinate of the window's upper-left corner.",
      },
      {
        label: '$iWidth',
        documentation: "The window's new width, in pixels.",
      },
      {
        label: '$iHeight',
        documentation: "The window's new height, in pixels.",
      },
      {
        label: '$iFlags',
        documentation:
          'A combination of the following values that affect the size and position of the window.',
      },
    ],
  },
  _WinAPI_DefWindowProcW: {
    documentation:
      'Calls the default window procedure to provide default processing for any window messages',
    label: '_WinAPI_DefWindowProcW ( $hWnd, $iMsg, $wParam, $lParam )',
    params: [
      {
        label: '$hWnd',
        documentation: 'A handle to the window procedure that received the message.',
      },
      {
        label: '$iMsg',
        documentation: 'The message.',
      },
      {
        label: '$wParam',
        documentation:
          'Additional message-specific information. The content of this parameter depends on the message.',
      },
      {
        label: '$lParam',
        documentation:
          'Additional message-specific information. The content of this parameter depends on the message.',
      },
    ],
  },
  _WinAPI_DeregisterShellHookWindow: {
    documentation:
      'Unregisters a specified Shell window that is registered to receive Shell hook messages',
    label: '_WinAPI_DeregisterShellHookWindow ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to unregister from receiving Shell hook messages.',
      },
    ],
  },
  _WinAPI_DragAcceptFiles: {
    documentation: 'Registers whether a window accepts dropped files',
    label: '_WinAPI_DragAcceptFiles ( $hWnd [, $bAccept = True] )',
    params: [
      {
        label: '$hWnd',
        documentation:
          'Handle to the window that is registering whether it will accept dropped files.',
      },
      {
        label: '$bAccept',
        documentation:
          '**[optional]** Specifies whether a window accepts dropped files, valid values: True - Accept dropped files (Default). False - Discontinue accepting dropped files.',
      },
    ],
  },
  _WinAPI_DragFinish: {
    documentation:
      'Releases memory that the system allocated for use in transferring file names to the application',
    label: '_WinAPI_DragFinish ( $hDrop )',
    params: [
      {
        label: '$hDrop',
        documentation:
          'Handle of the drop structure that describes the dropped file. This parameter is passed to WM_DROPFILES message with WPARAM parameter.',
      },
    ],
  },
  _WinAPI_DragQueryFileEx: {
    documentation:
      'Retrieves the names of dropped files that result from a successful drag-and-drop operation',
    label: '_WinAPI_DragQueryFileEx ( $hDrop [, $iFlag = 0] )',
    params: [
      {
        label: '$hDrop',
        documentation:
          'Handle of the drop structure that describes the dropped file. This parameter is passed to WM_DROPFILES message with WPARAM parameter.',
      },
      {
        label: '$iFlag',
        documentation: '**[optional]** Controls the output type.',
      },
    ],
  },
  _WinAPI_DragQueryPoint: {
    documentation:
      'Retrieves the position of the mouse pointer at the time a file was dropped during a drag-and-drop operation',
    label: '_WinAPI_DragQueryPoint ( $hDrop )',
    params: [
      {
        label: '$hDrop',
        documentation:
          'Handle of the drop structure that describes the dropped file. This parameter is passed to WM_DROPFILES message with WPARAM parameter.',
      },
    ],
  },
  _WinAPI_EndDeferWindowPos: {
    documentation:
      'Simultaneously updates the position and size of one or more windows in a single screen-refreshing cycle',
    label: '_WinAPI_EndDeferWindowPos ( $hInfo )',
    params: [
      {
        label: '$hInfo',
        documentation:
          'Handle to a multiple-window-position structure that contains size and position information for one or more windows.',
      },
    ],
  },
  _WinAPI_EnumChildWindows: {
    documentation: 'Enumerates a child windows that belong to the specified parent window',
    label: '_WinAPI_EnumChildWindows ( $hWnd [, $bVisible = True] )',
    params: [
      {
        label: '$hWnd',
        documentation:
          'Handle to the parent window whose child windows are to be enumerated. If this parameter is 0, this function is equivalent to _WinAPI_EnumWindows().',
      },
      {
        label: '$bVisible',
        documentation:
          '**[optional]** Specifies whether enumerates the invisible window, valid values: True - Enumerate only visible windows (Default). False - Enumerate all windows.',
      },
    ],
  },
  _WinAPI_GetClassInfoEx: {
    documentation: 'Retrieves information about a window class',
    label: '_WinAPI_GetClassInfoEx ( $sClass [, $hInstance = 0] )',
    params: [
      {
        label: '$sClass',
        documentation:
          'The class name. The name must be that of a preregistered class or a class registered by a previous call to the _WinAPI_RegisterClass() or _WinAPI_RegisterClassEx() function.',
      },
      {
        label: '$hInstance',
        documentation:
          '**[optional]** Handle to the instance of the application that created the class.',
      },
    ],
  },
  _WinAPI_GetClassLongEx: {
    documentation: 'Retrieves the specified value associated with the specified window',
    label: '_WinAPI_GetClassLongEx ( $hWnd, $iIndex )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window.',
      },
      {
        label: '$iIndex',
        documentation: 'The value to retrieve. This parameter can be one of the following values.',
      },
    ],
  },
  _WinAPI_GetGUIThreadInfo: {
    documentation: 'Retrieves information about the active window or a specified GUI thread',
    label: '_WinAPI_GetGUIThreadInfo ( $iThreadId )',
    params: [
      {
        label: '$iThreadId',
        documentation: 'The identifier for the thread for which information is to be retrieved.',
      },
    ],
  },
  _WinAPI_GetLastActivePopup: {
    documentation:
      'Determines which pop-up window owned by the specified window was most recently active',
    label: '_WinAPI_GetLastActivePopup ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the owner window.',
      },
    ],
  },
  _WinAPI_GetMessageExtraInfo: {
    documentation: 'Retrieves the extra message information for the current thread',
    label: '_WinAPI_GetMessageExtraInfo ( )',
    params: [],
  },
  _WinAPI_GetMonitorInfo: {
    documentation: 'Retrieves information about a display monitor',
    label: '_WinAPI_GetMonitorInfo ( $hMonitor )',
    params: [
      {
        label: '$hMonitor',
        documentation: 'A handle to the display monitor of interest.',
      },
    ],
  },
  _WinAPI_GetObjectInfoByHandle: {
    documentation: 'Retrieves information about a specified object',
    label: '_WinAPI_GetObjectInfoByHandle ( $hObject )',
    params: [
      {
        label: '$hObject',
        documentation: 'A handle to the object to obtain information about.',
      },
    ],
  },
  _WinAPI_GetObjectNameByHandle: {
    documentation: 'Retrieves a name of the specified object',
    label: '_WinAPI_GetObjectNameByHandle ( $hObject )',
    params: [
      {
        label: '$hObject',
        documentation: 'A handle to the object to obtain its name.',
      },
    ],
  },
  _WinAPI_GetShellWindow: {
    documentation: "Retrieves a handle to the Shell's desktop window",
    label: '_WinAPI_GetShellWindow ( )',
    params: [],
  },
  _WinAPI_GetTopWindow: {
    documentation: 'Retrieves a handle to the child window at the top of the Z order',
    label: '_WinAPI_GetTopWindow ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation:
          'Handle to the parent window whose child windows need examination. When set to 0, the function retrieves a handle to the window at the top of the Z order.',
      },
    ],
  },
  _WinAPI_GetWindowDisplayAffinity: {
    documentation:
      'Retrieves the current display affinity setting, from any process, for a given window',
    label: '_WinAPI_GetWindowDisplayAffinity ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window for which display affinity setting is retrieved.',
      },
    ],
  },
  _WinAPI_GetWindowInfo: {
    documentation: 'Retrieves information about the specified window',
    label: '_WinAPI_GetWindowInfo ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window whose information is to be retrieved.',
      },
    ],
  },
  _WinAPI_GetWorkArea: {
    documentation: 'Retrieves the size of the working area on the primary display monitor',
    label: '_WinAPI_GetWorkArea ( )',
    params: [],
  },
  _WinAPI_IsChild: {
    documentation: 'Tests whether a window is a child window of a specified parent window',
    label: '_WinAPI_IsChild ( $hWnd, $hWndParent )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to be tested.',
      },
      {
        label: '$hWndParent',
        documentation: 'Handle to the parent window.',
      },
    ],
  },
  _WinAPI_IsHungAppWindow: {
    documentation: 'Determines whether the specified application is not responding',
    label: '_WinAPI_IsHungAppWindow ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window.',
      },
    ],
  },
  _WinAPI_IsIconic: {
    documentation: 'Determines whether the specified window is minimized (iconic)',
    label: '_WinAPI_IsIconic ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to test.',
      },
    ],
  },
  _WinAPI_IsWindowUnicode: {
    documentation: 'Determines whether the specified window is a native Unicode window',
    label: '_WinAPI_IsWindowUnicode ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to test.',
      },
    ],
  },
  _WinAPI_IsZoomed: {
    documentation: 'Determines whether a window is maximized',
    label: '_WinAPI_IsZoomed ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to test.',
      },
    ],
  },
  _WinAPI_KillTimer: {
    documentation: 'Destroys the specified timer',
    label: '_WinAPI_KillTimer ( $hWnd, $iTimerID )',
    params: [
      {
        label: '$hWnd',
        documentation:
          'Handle to the window associated with the specified timer. This value must be the same as the $hWnd value passed to the _WinAPI_SetTimer() function that created the timer.',
      },
      {
        label: '$iTimerID',
        documentation: 'The timer identifier which specifies the timer to be destroyed.',
      },
    ],
  },
  _WinAPI_OpenIcon: {
    documentation:
      'Restores a minimized (iconic) window to its previous size and position and activates the window',
    label: '_WinAPI_OpenIcon ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to be restored and activated.',
      },
    ],
  },
  _WinAPI_RegisterClass: {
    documentation: 'Registers a window class',
    label: '_WinAPI_RegisterClass ( $tWNDCLASS )',
    params: [
      {
        label: '$tWNDCLASS',
        documentation: '$tagWNDCLASS structure',
      },
    ],
  },
  _WinAPI_RegisterClassEx: {
    documentation: 'Registers a window class',
    label: '_WinAPI_RegisterClassEx ( $tWNDCLASSEX )',
    params: [
      {
        label: '$tWNDCLASSEX',
        documentation: '$tagWNDCLASSEX structure.',
      },
    ],
  },
  _WinAPI_RegisterShellHookWindow: {
    documentation:
      'Registers a specified Shell window to receive certain messages for events or notifications',
    label: '_WinAPI_RegisterShellHookWindow ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window to register for Shell hook messages.',
      },
    ],
  },
  _WinAPI_SendMessageTimeout: {
    documentation: 'Sends the specified message to one of more windows',
    label:
      '_WinAPI_SendMessageTimeout ( $hWnd, $iMsg [, $wParam = 0 [, $lParam = 0 [, $iTimeout = 1000 [, $iFlags = 0]]]] )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window whose window procedure will receive the message.',
      },
      {
        label: '$iMsg',
        documentation: 'The message to be sent.',
      },
      {
        label: '$wParam',
        documentation: '**[optional]** The message-specific information.',
      },
      {
        label: '$lParam',
        documentation: '**[optional]** The message-specific information.',
      },
      {
        label: '$iTimeout',
        documentation:
          '**[optional]** The duration, in milliseconds, of the time-out period. If the message is a broadcast message, each window can use the full time-out period.',
      },
      {
        label: '$iFlags',
        documentation:
          '**[optional]** The flags that specifies how to send the message. This parameter can be one or more of the following values: $SMTO_BLOCK, $SMTO_NORMAL, $SMTO_ABORTIFHUNG, $SMTO_NOTIMEOUTIFNOTHUNG, $SMTO_ERRORONEXIT.',
      },
    ],
  },
  _WinAPI_SetClassLongEx: {
    documentation: 'Replaces the specified value into the specified window belongs',
    label: '_WinAPI_SetClassLongEx ( $hWnd, $iIndex, $iNewLong )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window.',
      },
      {
        label: '$iIndex',
        documentation:
          'The value to be replaced. This parameter can be one of the following values',
      },
      {
        label: '$iNewLong',
        documentation: 'The replacement value.',
      },
    ],
  },
  _WinAPI_SetForegroundWindow: {
    documentation: 'Puts the specified window into the foreground and activates its',
    label: '_WinAPI_SetForegroundWindow ( $hWnd )',
    params: [
      {
        label: '$hWnd',
        documentation:
          'Handle to the window that should be activated and brought to the foreground.',
      },
    ],
  },
  _WinAPI_SetMessageExtraInfo: {
    documentation: 'Sets the extra message information for the current thread',
    label: '_WinAPI_SetMessageExtraInfo ( $lParam )',
    params: [
      {
        label: '$lParam',
        documentation: 'The value of lParam type to be associated with the current thread.',
      },
    ],
  },
  _WinAPI_SetTimer: {
    documentation: 'Creates a timer with the specified time-out value',
    label: '_WinAPI_SetTimer ( $hWnd, $iTimerID, $iElapse, $pTimerFunc )',
    params: [
      {
        label: '$hWnd',
        documentation:
          'Handle to the window to be associated with the timer. This window must be owned by the calling process.',
      },
      {
        label: '$iTimerID',
        documentation: 'The timer identifier.',
      },
      {
        label: '$iElapse',
        documentation: 'The time-out value, in milliseconds.',
      },
      {
        label: '$pTimerFunc',
        documentation:
          'The address of a callback function to be notified when the time-out value elapses. If this parameter is 0, the system posts a WM_TIMER message to the application queue.',
      },
    ],
  },
  _WinAPI_SetWindowDisplayAffinity: {
    documentation: 'Stores the display affinity setting in kernel mode on the specified window',
    label: '_WinAPI_SetWindowDisplayAffinity ( $hWnd, $iAffinity )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window.',
      },
      {
        label: '$iAffinity',
        documentation:
          "The display affinity setting. This setting specifies where the window's contents are can be displayed. Set this value to $WDA_MONITOR to display the window's contents only on a monitor. Set this value to $WDA_NONE to remove the monitor-only affinity.",
      },
    ],
  },
  _WinAPI_ShowOwnedPopups: {
    documentation: 'Shows or hides all pop-up windows owned by the specified window',
    label: '_WinAPI_ShowOwnedPopups ( $hWnd, $bShow )',
    params: [
      {
        label: '$hWnd',
        documentation: 'A handle to the window that owns the pop-up windows to be shown or hidden.',
      },
      {
        label: '$bShow',
        documentation:
          'Controls the visibility state of popup windows. True = All hidden pop-up windows are shown; False = All visible pop-up windows are hidden.',
      },
    ],
  },
  _WinAPI_SwitchToThisWindow: {
    documentation: 'Switches the focus to a specified window and bring it to the foreground',
    label: '_WinAPI_SwitchToThisWindow ( $hWnd [, $bAltTab = False] )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window being switched to.',
      },
      {
        label: '$bAltTab',
        documentation:
          '**[optional]** Specifies whether switches to using the Alt/Ctl+Tab key sequence, valid values: True - The window is being switched to using the Alt/Ctl+Tab key sequence. False - Otherwise (Default).',
      },
    ],
  },
  _WinAPI_TileWindows: {
    documentation: 'Tiles the specified child windows of the specified parent window',
    label:
      '_WinAPI_TileWindows ( $aWnds [, $tRECT = 0 [, $hParent = 0 [, $iFlags = 0 [, $iStart = 0 [, $iEnd = -1]]]]] )',
    params: [
      {
        label: '$aWnds',
        documentation:
          'The array of handles to the child windows to arrange. If a specified child window is a top-level window with the style $WS_EX_TOPMOST or $WS_EX_TOOLWINDOW, the child window is not arranged. If this parameter is 0, all child windows of the specified parent window (or of the desktop window) are arranged.',
      },
      {
        label: '$tRECT',
        documentation:
          '**[optional]** $tagRECT structure that specifies the rectangular area, in client coordinates, within which the windows are arranged. If this parameter is 0 (Default), the client area of the parent window is used.',
      },
      {
        label: '$hParent',
        documentation:
          '**[optional]** Handle to the parent window. If this parameter is 0 (Default), the desktop window is assumed.',
      },
      {
        label: '$iFlags',
        documentation:
          '**[optional]** A cascade flag. This parameter can be one or more of the following values. $MDITILE_HORIZONTAL or $MDITILE_VERTICAL (Default)',
      },
      {
        label: '$iStart',
        documentation: '**[optional]** The index of array to start arranging at.',
      },
      {
        label: '$iEnd',
        documentation: '**[optional]** The index of array to stop arranging at.',
      },
    ],
  },
  _WinAPI_UnregisterClass: {
    documentation: 'Unregisters a window class, freeing the memory required for the class',
    label: '_WinAPI_UnregisterClass ( $sClass [, $hInstance = 0] )',
    params: [
      {
        label: '$sClass',
        documentation:
          'A null-terminated string or a class atom. If $sClass is a string, it specifies the window class name. This class name must have been registered by a previous call to the _WinAPI_RegisterClass() or _WinAPI_RegisterClassEx() function. If this parameter is an atom, it must be in the low-order word of $sClass; the high-order word must be zero.',
      },
      {
        label: '$hInstance',
        documentation:
          '**[optional]** Handle to the instance of the module that created the class.',
      },
    ],
  },
  _WinAPI_UpdateLayeredWindowEx: {
    documentation: 'Updates a bitmap translucency of a layered window',
    label:
      '_WinAPI_UpdateLayeredWindowEx ( $hWnd, $iX, $iY, $hBitmap [, $iOpacity = 255 [, $bDelete = False]] )',
    params: [
      {
        label: '$hWnd',
        documentation:
          'Handle to a layered window. A layered window is created by specifying $WS_EX_LAYERED when its creating.',
      },
      {
        label: '$iX',
        documentation: 'The new position of the left side of the window.',
      },
      {
        label: '$iY',
        documentation: 'The new position of the top of the window.',
      },
      {
        label: '$hBitmap',
        documentation: 'Handle to the bitmap that will be set to the layered window.',
      },
      {
        label: '$iOpacity',
        documentation:
          '**[optional]** The alpha transparency value to be used on the entire source bitmap.',
      },
      {
        label: '$bDelete',
        documentation:
          '**[optional]** Determines whether the bitmap is removed after the window updates.',
      },
    ],
  },
  _WinAPI_UpdateLayeredWindowIndirect: {
    documentation:
      'Updates the position, size, shape, content, and translucency of a layered window',
    label: '_WinAPI_UpdateLayeredWindowIndirect ( $hWnd, $tULWINFO )',
    params: [
      {
        label: '$hWnd',
        documentation:
          'Handle to a layered window. A layered window is created by specifying $WS_EX_LAYERED when its creating.',
      },
      {
        label: '$tULWINFO',
        documentation:
          '$tagUPDATELAYEREDWINDOWINFO structure that contains the information for the window.',
      },
    ],
  },
  _WinAPI_DefSubclassProc: {
    documentation: "Calls the next handler in a window's subclass chain",
    label: '_WinAPI_DefSubclassProc ( $hWnd, $iMsg, $wParam, $lParam )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle to the window being subclassed.',
      },
      {
        label: '$iMsg',
        documentation: 'The message to be sent.',
      },
      {
        label: '$wParam',
        documentation: 'The message-specific information.',
      },
      {
        label: '$lParam',
        documentation: 'The message-specific information.',
      },
    ],
  },
  _WinAPI_GetWindowSubclass: {
    documentation: 'Retrieves the reference data for the specified window subclass callback',
    label: '_WinAPI_GetWindowSubclass ( $hWnd, $pSubclassProc, $idSubClass )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle of the window being subclassed.',
      },
      {
        label: '$pSubclassProc',
        documentation:
          'A pointer to a window procedure. This pointer and the subclass ID uniquely identify this subclass callback.',
      },
      {
        label: '$idSubClass',
        documentation: 'The subclass ID.',
      },
    ],
  },
  _WinAPI_RemoveWindowSubclass: {
    documentation: 'Removes a subclass callback from a window',
    label: '_WinAPI_RemoveWindowSubclass ( $hWnd, $pSubclassProc, $idSubClass )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle of the window being subclassed.',
      },
      {
        label: '$pSubclassProc',
        documentation:
          'A pointer to a window procedure. This pointer and the subclass ID uniquely identify this subclass callback.',
      },
      {
        label: '$idSubClass',
        documentation: 'The subclass ID.',
      },
    ],
  },
  _WinAPI_SetWindowSubclass: {
    documentation: 'Installs or updates a window subclass callback',
    label: '_WinAPI_SetWindowSubclass ( $hWnd, $pSubclassProc, $idSubClass [, $pData = 0] )',
    params: [
      {
        label: '$hWnd',
        documentation: 'Handle of the window being subclassed.',
      },
      {
        label: '$pSubclassProc',
        documentation:
          'A pointer to a window procedure. This pointer and the subclass ID uniquely identify this subclass callback.',
      },
      {
        label: '$idSubClass',
        documentation: 'The subclass ID.',
      },
      {
        label: '$pData',
        documentation:
          '**[optional]** The reference data. This value is passed to the subclass procedure. The meaning of this value is determined by the calling application.',
      },
    ],
  },
};

const hovers = signatureToHover(signatures);
const completions = signatureToCompletion(signatures, CompletionItemKind.Function, include);

export { signatures as default, hovers, completions };
