const DEFAULT_UDFS = [
  'APIComConstants',
  'APIConstants',
  'APIDiagConstants',
  'APIDlgConstants',
  'APIErrorsConstants',
  'APIFilesConstants',
  'APIGdiConstants',
  'APILocaleConstants',
  'APIMiscConstants',
  'APIProcConstants',
  'APIRegConstants',
  'APIResConstants',
  'APIShellExConstants',
  'APIShPathConstants',
  'APISysConstants',
  'APIThemeConstants',
  'Array',
  'AutoItConstants',
  'AVIConstants',
  'BorderConstants',
  'ButtonConstants',
  'Clipboard',
  'Color',
  'ColorConstants',
  'ComboConstants',
  'Constants',
  'Crypt',
  'Date',
  'DateTimeConstants',
  'Debug',
  'DirConstants',
  'EditConstants',
  'EventLog',
  'Excel',
  'ExcelConstants',
  'File',
  'FileConstants',
  'FontConstants',
  'FrameConstants',
  'FTPEx',
  'GDIPlus',
  'GDIPlusConstants',
  'GuiAVI',
  'GuiButton',
  'GuiComboBox',
  'GuiComboBoxEx',
  'GUIConstants',
  'GUIConstantsEx',
  'GuiDateTimePicker',
  'GuiEdit',
  'GuiHeader',
  'GuiImageList',
  'GuiIPAddress',
  'GuiListBox',
  'GuiListView',
  'GuiMenu',
  'GuiMonthCal',
  'GuiReBar',
  'GuiRichEdit',
  'GuiScrollBars',
  'GuiSlider',
  'GuiStatusBar',
  'GuiTab',
  'GuiToolbar',
  'GuiToolTip',
  'GuiTreeView',
  'HeaderConstants',
  'IE',
  'ImageListConstants',
  'Inet',
  'InetConstants',
  'IPAddressConstants',
  'ListBoxConstants',
  'ListViewConstants',
  'Math',
  'MathConstants',
  'Memory',
  'MemoryConstants',
  'MenuConstants',
  'Misc',
  'MsgBoxConstants',
  'NamedPipes',
  'NetShare',
  'NTSTATUSConstants',
  'Process',
  'ProcessConstants',
  'ProgressConstants',
  'RebarConstants',
  'RichEditConstants',
  'ScreenCapture',
  'ScrollBarConstants',
  'ScrollBarsConstants',
  'Security',
  'SecurityConstants',
  'SendMessage',
  'SliderConstants',
  'Sound',
  'SQLite',
  'SQLite.dll',
  'StaticConstants',
  'StatusBarConstants',
  'String',
  'StringConstants',
  'StructureConstants',
  'TabConstants',
  'Timers',
  'ToolbarConstants',
  'ToolTipConstants',
  'TrayConstants',
  'TreeViewConstants',
  'UDFGlobalID',
  'UpDownConstants',
  'Visa',
  'WinAPI',
  'WinAPICom',
  'WinAPIConstants',
  'WinAPIDiag',
  'WinAPIDlg',
  'WinAPIError',
  'WinAPIEx',
  'WinAPIFiles',
  'WinAPIGdi',
  'WinAPIInternals',
  'WinAPIlangConstants',
  'WinAPILocale',
  'WinAPIMisc',
  'WinAPIProc',
  'WinAPIReg',
  'WinAPIRes',
  'WinAPIShellEx',
  'WinAPIShPath',
  'WinAPISys',
  'WinAPIsysinfoConstants',
  'WinAPITheme',
  'WinAPIvkeysConstants',
  'WindowsConstants',
  'WinNet',
  'Word',
  'WordConstants',
];

/**
 * Formatter constants for AutoIt Tidy and backup operations
 */
const FORMATTER = {
  TEMP_FILE_PREFIX: 'temp_format_',
  BACKUP_DIR_NAME: 'BackUp',
  BACKUP_FILE_SUFFIX: '_old1.au3',
  BACKUP_FILE_SUFFIX_PATTERN: /_old\d*\.au3$/i,
  TIDY_TIMEOUT_MS: 10000, // Increased timeout for better reliability
  FILE_EXTENSION: '.au3',
};

const DEFAULT_MAX_INCLUDE_DEPTH = 3;
const DEFAULT_PARSE_DEBOUNCE_MS = 500;

export { DEFAULT_UDFS, FORMATTER, DEFAULT_MAX_INCLUDE_DEPTH, DEFAULT_PARSE_DEBOUNCE_MS };
